-- NOTE 
-- lua require("plenary.test_harness").test_file("tests/test_ccsds.lua")

describe("ccsds", function()
    it("can be required", function()
        require("ccsds-hdr")
    end)
    it("can call test1", function()
        require("ccsds-hdr").test1()
    end)
    it("can call test2", function()
        require("ccsds-hdr").test2()
    end)
    it("can retreive keymaps and config", function()
        local config = require("ccsds-hdr.config")
        local maps = config.get_keymap()
        local cfgs = config.get_config()
        assert.equals(maps.test1, cfgs.keymaps.test1)
        assert.equals(maps.test2, cfgs.keymaps.test2)
    end)
end)
