-- NOTE 
-- lua require("plenary.test_harness").test_file("tests/test_ccsds.lua")
local util = require("ccsds-hdr.utils")
local conf = require("ccsds-hdr.config")

describe("Module: utils.lua, Function: is_valid_table_key", function()
    it("should return a valid value that corresponds to the key passed", function()
        local result = util.is_valid_table_key(conf.cfg, "keymaps.test1.mode")
        assert.are.equal(result, conf.cfg.keymaps.test1.mode)
    end)
    it("should immediately raise an error on the first invalid key", function()
        assert.has.error(function()
            util.is_valid_table_key(conf.cfg, "this.is.a.bad.key")
        end, "Invalid key: Key 'this' does not exist.")
    end)
end)
